version: '3.8'

services:
  loa-helper-latest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loa-helper-latest
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app